version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8002:8002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/product_store
      - JWT_SECRET=supersecuresecret
    depends_on:
      - mongo
    networks:
      - mern-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mern-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
